DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;
CREATE TABLE burgers(

id INT AUTO_INCREMENT NOT NULL,

burger_name VARCHAR(100) NOT NULL,
devoured BOOLEAN DEFAULT false,
ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY(id)
);